# Generated by Django 6.0.2 on 2026-02-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_alter_postmodel_options_alter_postmodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='postmodel',
            table=None,
        ),
    ]
