# Generated by Django 6.0.2 on 2026-02-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0004_alter_postmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
