# Generated by Django 6.0.2 on 2026-02-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='text',
            field=models.TextField(default=None, max_length=100000),
        ),
    ]
