# Generated by Django 6.0.2 on 2026-02-19 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0007_tag_comment_postmodel_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
